### ISSUE TITLE
New weekly post has posts that were also included in previous weekly post.

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/bestofbot#11]
https://lemmy.dbzer0.com/post/22446189 New post.

https://lemmy.dbzer0.com/post/22096481 Old post.

**Comment by chris-y** [comment]
Seems OK this week.

We have federation issues though, as nothing from lemmydirectory is federating to feddit.uk

I'll raise it with them, not sure which side is causing problems.

**Comment by M4rtineski** [comment]
WHAT THE FUUUUUUUCK. It's been already 2 weeks? When did that time fly by? I thought we worked on it only for a few days so far. 💀

**Comment by M4rtineski** [comment]
![image](https://github.com/fnic-lemmy/bestofbot/assets/137183342/02ea9ff9-9b46-402c-995b-8b26b4622611)
Can you change the look of those to be consistent with the directory? It's hard to read white text on bright green background. Also sharp corners are ugly. xd
