### ISSUE TITLE
Monthly posts

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/bestofbot#13]
Should be fortnightly rather than weekly!

**Comment by chris-y** [comment]
Cron is a PITA to do every two weeks...

**Comment by M4rtineski** [comment]
Huh? What makes it harder to set up than 1 week?

**Comment by chris-y** [comment]
You can do a time, a day of the week, a day of the month, weekly in fine because every whatever-day is easy, two weekly you're having to skip days and because there's no "week of year" option it's not that simple.

**Comment by M4rtineski** [comment]
Oof. I thought you just make it do math to work every x amount of time and that's it. Well good luck I guess. haha

**Comment by chris-y** [comment]
Discussion here about making it monthly: 
https://github.com/fnic-lemmy/bestofbot/issues/7#issuecomment-2189982317_

**Comment by M4rtineski** [comment]
When we have it set up monthly let's add the schedule to the introduction post on the directory.

**Comment by chris-y** [comment]
Schedule calendar: https://use10.thegood.cloud/apps/calendar/p/dFMpSoX7FPf6EyYX

**Comment by chris-y** [comment]
I'm queuing up my bots in #7 - when I have a reasonable number I'll reconfigure to run monthly and schedule them across the month.

**Comment by chris-y** [comment]
I've changed the calendar from the 1st August to run monthly (this may mean the previously weekly bots will post similar things to the previous month on their first run on the new schedule).  I need to remember to do the necessary admin late on the 31st to make the bot post TopMonth instead of TopWeek, as well as changing the triggers for the current weekly bots.

There are some gaps that can be filled later, but I've tried to keep similar things at weekly intervals.

**Comment by M4rtineski** [comment]
Wait, it's already set to monthly? We don't have nearly enough categories for that. Are you running a bot every 2-3 days perhaps?

**Comment by chris-y** [comment]
Every 1-2 days.  There are nine gaps plus 29-31 which I'm not sure what to do with.
The gaps are spaced out so a couple of days a week there won't be any, but we can fill those later.
I'm not activating this until August.

**Comment by M4rtineski** [comment]
Shouldn't we just disable it until the time for monthly posts comes? The content is going to repeat anyway.
