### ISSUE TITLE
I think the communities in the "inactive communities" section should be in order they're in in the directory.

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/bestofbot#25]
![image](https://github.com/fnic-lemmy/bestofbot/assets/137183342/dc3d4336-daf8-4c11-9eba-50e204d70a56)

**Comment by chris-y** [comment]
I've removed the sorting which should resolve this.

**Comment by M4rtineski** [comment]
What did the sorting do and why it was there?

**Comment by chris-y** [comment]
Sorted them alphabetically.
The latest post shows this is now in directory order.
