### ISSUE TITLE
Save markdown copy for each crawl.

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/bestofbot#28]
![image](https://github.com/fnic-lemmy/bestofbot/assets/137183342/99829409-8f27-48f4-a165-8d26774e1fbd)

lose*

**Comment by chris-y** [comment]
The log is useless for this, although it dumps the markdown there are timestamps and things which prevent it from being copied easily.

**Comment by M4rtineski** [comment]
Pain.

**Comment by chris-y** [comment]
I'm seeing if there's a way I can save it back to GitHub.

**Comment by M4rtineski** [comment]
I was about to suggest just copying the markdown from the lemmy post after it got posted and then realised why we have this issue in the first place. xD

**Comment by M4rtineski** [comment]
![image](https://github.com/fnic-lemmy/bestofbot/assets/137183342/9c1ef116-f7b2-4a53-b694-bbf0de24bf6f)
