### ISSUE TITLE
Using one bot to lock posts instead of having each bot modded just so it could lock it's own posts.

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/bestofbot#30]
I don't want to have ~30 bots set as moderators for the directory. lmao

**Comment by M4rtineski** [comment]
I don't really want to use the directory account for that to avoid setting it as a bot.

**Comment by chris-y** [comment]
Probably best to use fnicmodbot

**Comment by M4rtineski** [comment]
Agree.

**Comment by chris-y** [comment]
Done.  Note the mod user needs to be on the same instance as the posting user, otherwise the post IDs won't match.
So we use fnicmodbot for most of them, but the Anime posts are posted from a different instance so that account will still need mod rights.

**Comment by M4rtineski** [comment]
This much is alright.
