### ISSUE TITLE
Dates or date ranges in post titles?

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/bestofbot#34]
I know it was already rejected but I was thinking of going back to certain posts at some point in the future to add the emojis to categories that didn't have them at the time and realised it would mess up the time shown in the post.

![image](https://github.com/fnic-lemmy/bestofbot/assets/137183342/b62508b7-f856-44a5-8560-6490ec8f4c54)

Same issue would resurface if we went back to edit the posts manually in any way. Be it broken images, formatting, small changes in something to align it with the new post format etc.

Personally I'd want to use absolute dates like dd.mm.yyyy and skip the hour because such a small detail is irrelevant anyway.

**Comment by chris-y** [comment]
Agreed, no point in putting the time as we aren't posting multiple per day. 

Adding the date is easy enough.
