### ISSUE TITLE
Indicate whether post is a picture, video or link

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/bestofbot#40]
It's confusing looking at the non-image-only posts, as you're not quite sure whether something is a picture, or the picture I've embedded is from a video thumbnail or article.

Suggest adding emojis as follows to article title;
📰 (article)
🖼️ (image)
📽️ (video)

As I put the title in before I know what it is, this might need to go underneath or I might have to do some rejigging to get it in the title.

**Comment by chris-y** [comment]
Article will be the catch-all for when we don't know what it is.  Might to check for embed_video_url alongside any other checks to help with finding videos.

We also need an emoji for plain text for when there is no link, suggest 🗩

**Comment by chris-y** [comment]
We might be able to do quite an easy check before putting the title in:
```
if no url: 🗩
if url, and content-type is image: 🖼️
if url and content-type is video, or embed_video_url: 📽️
if url and nothing else applies: 📰
```

**Comment by M4rtineski** [comment]
![image](https://github.com/fnic-lemmy/bestofbot/assets/137183342/5db452d8-6170-4ec7-babf-4752a28b437e)

The video emoji is barely visible with black background. I suggest we use this one instead: 🎦

**Comment by chris-y** [comment]
Reopening as the latest photography post has quite a few "article" emojis, despite that one being set to images only.
