### ISSUE TITLE
Add a note stating how posts are scored.

### ISSUE THREAD

**Issue by M4rtineski** [fnic-lemmy/bestofbot#45]
I noticed that I have no idea if it crawls total upvotes or score so it would be good to have it mentioned at the end of the post.

**Comment by chris-y** [comment]
It uses the score (which I believe is upvotes - downvotes).  I put that in brackets after the title.  Perhaps it needs an Emoji there?  Or maybe I need to put 👍upvotes 👎downvotes to make it clearer (and still rank by score as it makes more sense).

**Comment by M4rtineski** [comment]
I think having both upvotes and downvotes shown and having posts ranked by score would be good. There would be still a need to clarify that it's ranked by score unless you decide to keep this metric as well. And what do you mean by "after the title"? Do you mean in the title at the end or in the top of post's body?

**Comment by chris-y** [comment]
In the title at the end.

**Comment by M4rtineski** [comment]
Yeah, I don't think this stuff should be in the title. It's a note like any other. There's no reason for each daily post to have explanation on how posts are ranked in the title. Imo this should be just a note at the end of the post because once you learn it you don't need the constant reminder about that.

**Comment by chris-y** [comment]
Ah, no, this is the ranking in the title, not the explanation which hasn't been added yet.

**Comment by M4rtineski** [comment]
I just reread the thread and it clicked for me. I thought you meant the title of the 'best of' post and it ended up that way. Haha.

**Comment by M4rtineski** [comment]
Seems like an issue that we forgot to close.
