### ISSUE TITLE
AI summaries

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/bestofbot#53]
Black pen 🖋️ - TLDR;this (this seems to work really well)
Blue pen 🖊️ - pipfeed (new)

**Comment by chris-y** [comment]
Blue pen 🖊️ doesn't play well with Bandcamp, it seems to just pick up a load of user comments, needs blacklisting.

**Comment by M4rtineski** [comment]
Hmmmm, are you planning to implement some kind of summaries? I don't think I've heard of it before. Can you elaborate what is this exactly about because I can't imagine how would that work?

**Comment by chris-y** [comment]
It's just article summaries, they already have them, just trying some different options for generating them.

**Comment by chris-y** [comment]
https://yt.artemislena.eu/watch?v=EE2aECNMDRc (I've seen a couple of these) - I think these are just an alternative interface to YouTube, needs to be converted/summarised by the YouTube reader.

**Comment by M4rtineski** [comment]
I think this can be closed as well? Unless you plan to tinker with it more.
