### ISSUE TITLE
News memes needs renaming

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/bestofbot#54]
https://lemmy.dbzer0.com/post/27136391

~~Probably in the directory too.~~ Edit: I think the directory is fine, as it's actually "Memes/Humour" category, not just memes.

It's more weird news than news memes.

**Comment by chris-y** [comment]
^^ Above commit ^^ 
This category is articles, so images only was filtering out things it shouldn't be.

**Comment by chris-y** [comment]
> ^^ Above commit ^^ 
> This category is articles, so images only was filtering out things it shouldn't be. 
> 

I've deleted and re-posted it.

**Comment by M4rtineski** [comment]
I don't know where I mentioned it in the past but I was planning on changing the category name to "news format" but I'm still confused about where to categorise those articles. Is memes/humoristic category good enough? Or should they be somewhere else as some articles (or rather communities) are just about being weird and not humoristic.

**Comment by chris-y** [comment]
I'm not sure.  A "weird" or "news" category might be better?

**Comment by M4rtineski** [comment]
I think we can close it because we have the issue on the directory page.
