### ISSUE TITLE
Support text posts and video

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/bestofbot#8]
Doesn't support text posts - needs a URL and assumes it's a picture. 

Don't know if there is any way to tell if a URL isn't an image (from the Lemmy API)

**Comment by chris-y** [comment]
I did add a feature to force only images to be included.  This is a precursor to allowing other content types as they need to be handled differently to images, and some of our communities need the non-image posts filtered out as we want to showcase images, not accidentally get a META post featured.

**Comment by chris-y** [comment]
This needs to be the next thing I work on. 

I think we have four main types of posts; 
- [ ] Images
   - Images
These are already handled
- [ ] Text
   - Posts with just text and no link
Post a summary (first x characters) along with the title.
- [ ] URL
   - Posts with a link to another site/article
We could post a summary of the body, but sometimes there's nothing. Maybe summarise the website (if we can figure a sensible way of doing this) 
- [ ] Video
   - Posts with a video or link to a video
Ideally we need to post a thumbnail?

**Comment by M4rtineski** [comment]
@chris-y Do NOT include the body or if you want to make it a setting to disable it for specific communities. Dad jokes for example has punchlines in the body and that would spoiler it.

**Comment by chris-y** [comment]
Opened #36 which we might need for videos.

**Comment by chris-y** [comment]
Need to check what we get as URL for the top post when it doesn't contain an image.

**Comment by chris-y** [comment]
I think this is done bar allowing the description to be disabled.  That will wait until we have a community which requires it.

**Comment by M4rtineski** [comment]
Isn't this issue completed?
